export class Comarca{
   public values = [
        "Abreu e Lima",
        "Afogados da Ingazeira",
        "Afrânio",
        "Agrestina",
        "Água Preta",
        "Águas Belas",
        "Alagoinha",
        "Aliança",
        "Altinho",
        "Amaraji",
        "Angelim ",
        "Araripina",
        "Arcoverde",
        "Barreiros",
        "Belém de Maria",
        "Belém do São Francisco",
        "Belo Jardim",
        "Betânia",
        "Bezerros",
        "Bodocó",
        "Bom Conselho",
        "Bom Jardim",
        "Bonito",
        "Brejão",
        "Brejo da Madre de Deus",
        "Buenos Aires",
        "Buíque",
        "Cabo de Santo Agostinho",
        "Cabo de Santo Agostinho",
        "Cabrobó",
        "Cachoeirinha",
        "Caetés",
        "Calçado",
        "Camaragibe",
        "Camocim de São Félix",
        "Canhotinho",
        "Capoeiras",
        "Carnaíba",
        "Carpina",
        "Caruaru",
        "Catende",
        "Chã Grande",
        "Condado",
        "Correntes",
        "Cortês",
        "Cumaru",
        "Cupira",
        "Custódia",
        "Escada",
        "Exu",
        "Feira Nova",
        "Ferreiros",
        "Flores",
        "Floresta",
        "Gameleira",
        "Garanhuns",
        "Glória do Goitá",
        "Goiana",
        "Gravatá",
        "Iati",
        "Ibimirim",
        "Ibirajuba",
        "Igarassu",
        "Igarassu",
        "Inajá",
        "Ipojuca",
        "Ipubi",
        "Itaiba",
        "Itamaracá",
        "Itambé",
        "Itapetim",
        "Itapissuma",
        "Itaquitinga",
        "Jaboatão dos Guararapes",
        "Jataúba",
        "João Alfredo",
        "Joaquim Nabuco",
        "Jupi",
        "Jurema",
        "Lagoa do Itaenga",
        "Lagoa do Ouro",
        "Lagoa dos Gatos",
        "Lagoa Grande",
        "Lajedo",
        "Limoeiro",
        "Macaparana",
        "Maraial",
        "Mirandiba",
        "Moreilandia",
        "Moreno",
        "Nazaré da Mata",
        "Olinda",
        "Olinda",
        "Orobó",
        "Orocó",
        "Ouricuri",
        "Palmares",
        "Palmeirina",
        "Panelas",
        "Parnamirim",
        "Passira",
        "Paudalho",
        "Paulista",
        "Pedra",
        "Pesqueira",
        "Petrolândia",
        "Petrolina",
        "Petrolina",
        "Poção",
        "Pombos",
        "Primavera",
        "Quipapá",
        "Recife",
        "Riacho das Almas",
        "Ribeirão",
        "Rio Formoso",
        "Sairé",
        "Salgueiro",
        "Saloá",
        "Sanharó",
        "Santa Cruz do Capibaribe",
        "Santa Maria da Boa Vista",
        "Santa Maria do Cambucá",
        "São Bento do Una",
        "São Caetano",
        "São João",
        "São Joaquim do Monte",
        "São José da Coroa Grande",
        "São José do Belmonte",
        "São José do Egito",
        "São Lourenço da Mata",
        "São Vicente Férrer",
        "Serra Talhada",
        "Serrita",
        "Sertânia",
        "Sirinhaém",
        "Surubim",
        "Tabira",
        "Tacaimbó",
        "Tacaratu",
        "Tamandaré",
        "Taquaritinga do Norte",
        "Terra Nova",
        "Timbaúba",
        "Toritama",
        "Tracunhaém",
        "Trindade",
        "Triunfo",
        "Tuparetama",
        "Venturosa",
        "Verdejante",
        "Vertentes",
        "Vicência",
        "Vitória de Santo Antão"
    ]
}